"""Type stubs for can_motor_control."""

from __future__ import annotations

from collections.abc import Iterator
import sys
from typing import Any, ClassVar

import numpy as np

class DmError(Exception): ...
class TransportError(DmError): ...
class CodecError(DmError): ...
class ConfigError(DmError): ...
class LifecycleError(DmError): ...

class CanFrame:
    id: int
    flags: int
    len: int
    @classmethod
    def classical(cls, id: int, payload: bytes) -> "CanFrame": ...
    @classmethod
    def fd(cls, id: int, payload: bytes) -> "CanFrame": ...
    def payload(self) -> bytes: ...
    def is_fd(self) -> bool: ...
    def is_extended(self) -> bool: ...

class MockCanBus:
    def __init__(self, name: str) -> None: ...
    @staticmethod
    def new_fd(name: str) -> "MockCanBus": ...

if sys.platform == "linux":
    class SocketCanBus:
        def __init__(self, interface: str, fd: bool = False) -> None: ...
elif sys.platform == "darwin":
    class GsUsbDeviceInfo:
        @property
        def index(self) -> int: ...
        @property
        def vendor_id(self) -> int: ...
        @property
        def product_id(self) -> int: ...
        @property
        def serial_number(self) -> str | None: ...

    def list_gs_usb_devices(
        *, vendor_id: int, product_id: int
    ) -> list[GsUsbDeviceInfo]: ...

    class GsUsbBus:
        def __init__(
            self,
            *,
            vendor_id: int,
            product_id: int,
            serial_number: str | None = None,
            index: int | None = None,
            bitrate: int = 1_000_000,
            initialization_timeout: float = 5.0,
        ) -> None: ...
        @property
        def rx_received(self) -> int: ...
        @property
        def rx_dropped(self) -> int: ...
        @property
        def tx_accepted(self) -> int: ...
        @property
        def tx_completed(self) -> int: ...

class MockFeedbackCodec:
    def __init__(self, recv_id: int) -> None: ...

class MotorSpec:
    def __init__(self, name: str, type: int, send_id: int, recv_id: int) -> None: ...

class Motor:
    name: str
    send_id: int
    recv_id: int
    position: float
    velocity: float
    torque: float
    temperature_mos: int
    temperature_rotor: int
    is_enabled: bool
    fault: int | None

class Arm:
    def __len__(self) -> int: ...
    def __getitem__(self, name: str) -> Motor: ...
    def positions(self) -> np.ndarray: ...
    def velocities(self) -> np.ndarray: ...
    def torques(self) -> np.ndarray: ...
    def mit_control(self, cmds: np.ndarray) -> None: ...
    def pos_vel_control(self, cmds: np.ndarray) -> None: ...
    def vel_control(self, cmds: np.ndarray) -> None: ...
    def pos_force_control(self, cmds: np.ndarray) -> None: ...
    def enable_all(self) -> None: ...
    def disable_all(self) -> None: ...
    def set_zero_all(self) -> None: ...
    def refresh(self) -> None: ...
    def set_mode(self, mode: str) -> None: ...

class Gripper:
    @property
    def motor(self) -> Motor: ...
    @property
    def opening(self) -> float: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def mit_control(
        self, kp: float, kd: float, q: float, dq: float, tau: float
    ) -> None: ...
    def pos_vel_control(self, q: float, dq: float) -> None: ...
    def pos_force_control(self, q: float, dq: float, i_pu: float) -> None: ...
    def refresh(self) -> None: ...
    def set_mode(self, mode: str) -> None: ...
    def set_opening(self, opening: float, *, current: float | None = None) -> None: ...
    def open(self, *, current: float | None = None) -> None: ...
    def close(self, *, current: float | None = None) -> None: ...

class MotorGroup:
    def __len__(self) -> int: ...

class RobotBuilder:
    def __init__(self) -> None: ...
    def add_bus(
        self, name: str, transport: Any, codec: Any
    ) -> "RobotBuilder": ...
    def add_arm(
        self, name: str, *, bus: str, motors: list[MotorSpec]
    ) -> "RobotBuilder": ...
    def add_gripper(
        self,
        name: str,
        *,
        bus: str,
        motor: MotorSpec,
        opening_direction: str | None = None,
        default_current: float | None = None,
    ) -> "RobotBuilder": ...
    def add_generic(
        self, name: str, *, bus: str, motors: list[MotorSpec]
    ) -> "RobotBuilder": ...
    def build(self) -> "Robot": ...

class Robot:
    @classmethod
    def from_config(cls, path: str) -> "Robot": ...
    @classmethod
    def builder(cls) -> RobotBuilder: ...
    def connect(self) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def tick(self, per_bus_deadline_us: int) -> None: ...
    def refresh(self) -> None: ...
    def set_mode(self, mode: str) -> None: ...
    def __enter__(self) -> "Robot": ...
    def __exit__(self, *exc: Any) -> None: ...
    def __getitem__(self, name: str) -> Arm | Gripper | MotorGroup: ...
    def __contains__(self, name: str) -> bool: ...
    def group_names(self) -> list[str]: ...
    def bus_names(self) -> list[str]: ...
    def is_connected(self) -> bool: ...
